name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    name: CI - Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOC_SECRET }}

      - name: Set execute permission on mvnw
        run: chmod +x VIATabloid/NewsLetter/NewsletterSpringboot/SpringNews/mvnw

      - name: Build and Push Spring Boot Image
        working-directory: VIATabloid/NewsLetter/NewsletterSpringboot/SpringNews
        run: |
          ./mvnw package
          docker build . --tag ghcr.io/veronicatverdohleb/springnews:latest
          docker push ghcr.io/veronicatverdohleb/springnews:latest

      - name: Set up Node.js (for React)
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and Push React Image
        working-directory: VIATabloid/NewsLetter/NewsletterReactg/my-app
        run: |
          # Build your React application
          npm install
          npm run build
          # Build the Docker image for React
          docker build . --tag ghcr.io/veronicatverdohleb/my-app:latest
          docker push ghcr.io/veronicatverdohleb/my-app:latest

      - name: Build and Push PostgreSQL Image
        working-directory: VIATabloid/NewsLetter/NewsletterSpringboot/SpringNews
        run: |
          # You can use an official PostgreSQL image, so no build is required
          # Pull the official PostgreSQL image
          docker pull postgres:13
          # Tag and push it to your Docker registry
          docker build . --tag ghcr.io/veronicatverdohleb/postgresql:latest
          docker push ghcr.io/veronicatverdohleb/postgresql:latest
  trigger-cd-workflow:
    name: CD - Build and Deploy to Minikube
    uses: ./.github/workflows/cd-workflow.yaml
